from wordcloud import WordCloud
import matplotlib.pyplot as plt
import random
import pandas as pd
import datetime
from dateutil import parser
import re
from palettable.colorbrewer.sequential import Greys_9
from palettable.colorbrewer.sequential import Reds_9
from palettable.colorbrewer.sequential import Blues_9

dateparse = lambda x: pd.datetime.strptime(x, '%d/%m/%Y %H:%M')
df1 = pd.read_csv('label_visualisasi3/agussylvifixeditSS.csv', sep=',', parse_dates=['date'], date_parser=dateparse)
df2 = pd.read_csv('label_visualisasi3/ahokdjarotfixeditSS.csv', sep=',', parse_dates=['date'], date_parser=dateparse)
df3 = pd.read_csv('label_visualisasi3/aniessandifixeditSS.csv', sep=',', parse_dates=['date'], date_parser=dateparse)
font_path = "font/Mohave.otf"

def grey_color_func(word, font_size, position, orientation, random_state=None, **kwargs):
    return tuple(Greys_9.colors[random.randint(2,8)])

def red_color_func(word, font_size, position, orientation, random_state=None, **kwargs):
    return tuple(Reds_9.colors[random.randint(2,8)])

def blue_color_func(word, font_size, position, orientation, random_state=None, **kwargs):
    return tuple(Blues_9.colors[random.randint(2,8)])

#make wordcloud for the Candidate 1 
words_array = df3.text
str1 = ' '.join(str(e) for e in words_array)
str1 = re.sub(r'\bbapak\b', '', str1)
str1 = re.sub(r'\babang\b', '', str1)
str1 = re.sub(r'\bcuma\b', '', str1)
str1 = re.sub(r'\bjika\b', '', str1)
str1 = re.sub(r'\bbagaimana\b', '', str1)
str1 = re.sub(r'\btetapi\b', '', str1)
str1 = re.sub(r'\borang\b', '', str1)
str1 = re.sub(r'\bsaat\b', '', str1)
str1 = re.sub(r'\bjangan\b', '', str1)
str1 = re.sub(r'\bom\b', '', str1)
str1 = re.sub(r'\bmpok\b', '', str1)
str1 = re.sub(r'\biya\b', '', str1)
str1 = re.sub(r'\bnanti\b', '', str1)
str1 = re.sub(r'\bdulu\b', '', str1)
str1 = re.sub(r'\bsekarang\b', '', str1)
str1 = re.sub(r'\bmereka\b', '', str1)
str1 = re.sub(r'\bhanya\b', '', str1)
str1 = re.sub(r'\bsampai\b', '', str1)
str1 = re.sub(r'\bkenapa\b', '', str1)
str1 = re.sub(r'\bmemang\b', '', str1)
str1 = re.sub(r'\bibu\b', '', str1)
str1 = re.sub(r'\bsiapa\b', '', str1)
str1 = re.sub(r'\blo\b', '', str1)
str1 = re.sub(r'\bong\b', '', str1)
str1 = re.sub(r'\boleh\b', '', str1)
str1 = re.sub(r'\bterus\b', '', str1)
str1 = re.sub(r'\bbro\b', '', str1)
str1 = re.sub(r'\bayo\b', '', str1)
str1 = re.sub(r'\bmau\b', '', str1)
str1 = re.sub(r'\bingin\b', '', str1)
str1 = re.sub(r'\bspt\b', '', str1)
str1 = re.sub(r'\bmah\b', '', str1)
str1 = re.sub(r'\bseperti\b', '', str1)
str1 = re.sub(r'\bgitu\b', '', str1)
str1 = re.sub(r'\bpasti\b', '', str1)
str1 = re.sub(r'\bsemua\b', '', str1)
str1 = re.sub(r'\bkali\b', '', str1)
str1 = re.sub(r'\blihat\b', '', str1)
str1 = re.sub(r'\bmu\b', '', str1)
str1 = re.sub(r'\bpake\b', '', str1)
str1 = re.sub(r'\blain\b', '', str1)
str1 = re.sub(r'\bagar\b', '', str1)
str1 = re.sub(r'\bmasa\b', '', str1)
str1 = re.sub(r'\bkl\b', '', str1)
str1 = re.sub(r'\bcob\b', '', str1)
str1 = re.sub(r'\bdpt\b', '', str1)
str1 = re.sub(r'\bbegini\b', '', str1)
str1 = re.sub(r'\busah\b', '', str1)
str1 = re.sub(r'\btanya\b', '', str1)
str1 = re.sub(r'\bbs\b', '', str1)
str1 = re.sub(r'\bsm\b', '', str1)
str1 = re.sub(r'\btinggal\b', '', str1)
str1 = re.sub(r'\blebih\b', '', str1)
str1 = re.sub(r'\bdah\b', '', str1)
str1 = re.sub(r'\btu\b', '', str1)
str1 = re.sub(r'\bbanget\b', '', str1)
str1 = re.sub(r'\bdemi\b', '', str1)
str1 = re.sub(r'\bpernah\b', '', str1)
str1 = re.sub(r'\bhr\b', '', str1)
str1 = re.sub(r'\bmbak\b', '', str1)
str1 = re.sub(r'\bnama\b', '', str1)
str1 = re.sub(r'\bharap\b', '', str1)
str1 = re.sub(r'\bbagi\b', '', str1)
str1 = re.sub(r'\bbanyak\b', '', str1)
str1 = re.sub(r'\blbh\b', '', str1)
str1 = re.sub(r'\bmr\b', '', str1)
str1 = re.sub(r'\bwah\b', '', str1)
str1 = re.sub(r'\bhrs\b', '', str1)
str1 = re.sub(r'\bpas\b', '', str1)
str1 = re.sub(r'\bjam\b', '', str1)
str1 = re.sub(r'\bdapat\b', '', str1)
str1 = re.sub(r'\bcoba\b', '', str1)
str1 = re.sub(r'\bcerda\b', 'cerdas', str1)
str1 = re.sub(r'\btiap\b', '', str1)
str1 = re.sub(r'\bselalu\b', '', str1)
str1 = re.sub(r'\bsendiri\b', '', str1)
str1 = re.sub(r'\basal\b', '', str1)
str1 = re.sub(r'\btetap\b', '', str1)
str1 = re.sub(r'\bperlu\b', '', str1)
str1 = re.sub(r'\bmaksud\b', '', str1)
str1 = re.sub(r'\bcoblo\b', 'coblos', str1)
str1 = re.sub(r'\bberik\b', 'beri', str1)
str1 = re.sub(r'\bkalian\b', '', str1)
str1 = re.sub(r'\bbgt\b', '', str1)
str1 = re.sub(r'\bemang\b', '', str1)
str1 = re.sub(r'\bsalam\b', '', str1)
str1 = re.sub(r'\bsangat\b', '', str1)
str1 = re.sub(r'\bbilang\b', '', str1)
str1 = re.sub(r'\bart\b', 'arti', str1)
str1 = re.sub(r'\bmalah\b', '', str1)
str1 = re.sub(r'\bmakin\b', '', str1)
str1 = re.sub(r'\bpunya\b', '', str1)
str1 = re.sub(r'\bpara\b', '', str1)
str1 = re.sub(r'\bbegitu\b', '', str1)
str1 = re.sub(r'\bata\b', '', str1)
str1 = re.sub(r'\bmari\b', '', str1)
str1 = re.sub(r'\btanpa\b', '', str1)
str1 = re.sub(r'\bntar\b', '', str1)
str1 = re.sub(r'\bthn\b', '', str1)
str1 = re.sub(r'\bapalagi\b', '', str1)
str1 = re.sub(r'\bgin\b', '', str1)
str1 = re.sub(r'\bmakanya\b', '', str1)
str1 = re.sub(r'\bmungkin\b', '', str1)
str1 = re.sub(r'\bminta\b', '', str1)
str1 = re.sub(r'\bpaling\b', '', str1)
str1 = re.sub(r'\bbagai\b', '', str1)
str1 = re.sub(r'\bsemoga\b', '', str1)
str1 = re.sub(r'\bpadahal\b', '', str1)
str1 = re.sub(r'\bbakal\b', '', str1)
str1 = re.sub(r'\bni\b', '', str1)
str1 = re.sub(r'\bkayak\b', '', str1)
str1 = re.sub(r'\bboleh\b', '', str1)
str1 = re.sub(r'\bmending\b', '', str1)
str1 = re.sub(r'\btentu\b', '', str1)
str1 = re.sub(r'\bama\b', '', str1)
str1 = re.sub(r'\buru\b', '', str1)
str1 = re.sub(r'\bmrk\b', '', str1)
str1 = re.sub(r'\bkyk\b', '', str1)
str1 = re.sub(r'\bikut\b', '', str1)
str1 = re.sub(r'\batas\b', '', str1)
str1 = re.sub(r'\bsekal\b', '', str1)
str1 = re.sub(r'\bawal\b', '', str1)
str1 = re.sub(r'\bketika\b', '', str1)
str1 = re.sub(r'\bkapan\b', '', str1)
str1 = re.sub(r'\bwaktu\b', '', str1)
str1 = re.sub(r'\blangsung\b', '', str1)
str1 = re.sub(r'\btahun\b', '', str1)
str1 = re.sub(r'\bbung\b', '', str1)
str1 = re.sub(r'\bcagub\b', '', str1)
str1 = re.sub(r'\bpaslon\b', '', str1)

# end Agus-Sylvi

str1 = re.sub(r'\bgubernur\b', '', str1)
str1 = re.sub(r'\bkepada\b', '', str1)

# end Ahok-Djarot

str1 = re.sub(r'\bkata\b', '', str1)
str1 = re.sub(r'\bapakah\b', '', str1)
str1 = re.sub(r'\bpagi\b', '', str1)
str1 = re.sub(r'\bbeliau\b', '', str1)
str1 = re.sub(r'\bbahwa\b', '', str1)
str1 = re.sub(r'\bsbg\b', '', str1)
str1 = re.sub(r'\bsukse\b', 'sukses', str1)

str1 = str1.replace('aniessandi', '')

wc = WordCloud(font_path=font_path, background_color="white", max_words=300, max_font_size=300, width=800, height=400)
wc.generate(str1)
wc.recolor(color_func=blue_color_func)

plt.figure(figsize=(12,10))
plt.imshow(wc, interpolation='bilinear')
plt.axis("off")
plt.savefig("aniessandiWC4.png", bbox_inches='tight')
plt.show()